### ISSUE TITLE
efp: test for h > 1

### ISSUE THREAD

**Issue by GreatEmerald** [appelmar/strucchange#3]
If `h` in `efp` is set to an integer that is more than 1, this error is thrown:
```
Error in process[1:(n - nh + 1)] : 
  only 0's may be mixed with negative subscripts
```
Instead, the user should be told to use `h` values below 1 (or the function could calculate the `h` value on the fly).

**Comment by GreatEmerald** [comment]
I ran into this again yesterday, it's quite annoying. `bfast()` itself works fine with integer `h` values, but `epf` breaks down if that is attempted...
Relevant line:
https://github.com/appelmar/strucchange/blob/78d57129b45c0c5cf28cc69a3b19956ee0ac2486/R/efp.R#L137

**Comment by appelmar** [comment]
What exactly does bfast if  `h` > 1? For example, is `h` interpreted as the absolute number representing the minimal sample size between detected breaks instead of the fraction to the total time series length?  Or is it simply set to 1, or something else? I think it make sense to have the same behavior in bfast and strucchange.

**Comment by GreatEmerald** [comment]
The former, minimum segment size in discrete time steps.

**Comment by appelmar** [comment]
OK, so something like `if(h > 1) h = h / length(timeseries)` at the beginning of the function would be enough? Trying to do this later today, and adapt the docs.

**Comment by appelmar** [comment]
The case `h == 1` might be interesting. Would this represent a complete time series or a single time step?

**Comment by GreatEmerald** [comment]
Yes, that should be right.
`h == 1` should be an error, because neither makes sense; you can't find a break if you're looking on just a single time step, and if it's the whole time series as the minimum segment length, by definition you will find 0 breakpoints.

**Comment by appelmar** [comment]
@GreatEmerald Can you check whether it works for you now?

**Comment by GreatEmerald** [comment]
Yes, it works! Though in case of an `h` that is >1 and a fraction, `bfast()` still runs into the same issue as in #5. But then that's not exactly an `efp` issue, so this can be closed.
