### ISSUE TITLE
bfast/The number of breakpoints

### ISSUE THREAD

**Issue by xytu** [appelmar/strucchange#40]
(rdist <- 10/length(harvest))
fit <- bfast(harvest, h = rdist, season = "harmonic", max.iter = 5, breaks = 2)
#Here, when breaks=2, why  the results showed 3 breakpoints(one in the season component, the other two in the trend component)?
#Thanks for your answers.

**Comment by GreatEmerald** [comment]
I reproduced the bug and I see now what causes it:
https://github.com/bfast2/strucchangeRcpp/blob/master/R/breakpoints.R#L205
This line should only be run if breakstat is not `NULL`, otherwise it is not needed and it will not honour the "breaks" option. I will make a PR, please test it and let me know if it fixes the issue.

**Comment by GreatEmerald** [comment]
Please test the fix in #41.

**Comment by GreatEmerald** [comment]
Actually that is only a partial fix, please test together with https://github.com/bfast2/bfast/pull/103.

**Comment by xytu** [comment]
> I reproduced the bug and I see now what causes it: https://github.com/bfast2/strucchangeRcpp/blob/master/R/breakpoints.R#L205 This line should only be run if breakstat is not `NULL`, otherwise it is not needed and it will not honour the "breaks" option. I will make a PR, please test it and let me know if it fixes the issue.

**Comment by xytu** [comment]
> Huh, interesting, it should give four breakpoints, two in each component. This is apparently something in the breakpoints() function that should be debugged further. I'll move this to the strucchangeRcpp repository.

Well, when the breaks=3, 4, 5...., it gives the corresponding number of breakpoints in the trend component but none in the season trend. 
fit <- bfast(harvest, h = rdist, season = "harmonic")  #There is also no breakpoint in the seasonal component when set to 
                                                                                   #default.

**Comment by GreatEmerald** [comment]
Right, I found still one bug in strucchangeRcpp, and I now also made it possible to specify the number of breaks separately for the seasonal and the trend components. Now it seems to work correctly. Please test again.

Note that you can still get no breaks in some cases, e.g.:
```r
fit <- bfast(harvest, h = rdist, season = "harmonic", max.iter = 5, breaks = list(NULL, 4))
```
But this is because the sctest says there is no break, and the sctest overrides (runs prior to) bfast.

**Comment by xytu** [comment]
> Right, I found still one bug in strucchangeRcpp, and I now also made it possible to specify the number of breaks separately for the seasonal and the trend components. Now it seems to work correctly. Please test again.
> 
> Note that you can still get no breaks in some cases, e.g.:
> 
> ```r
> fit <- bfast(harvest, h = rdist, season = "harmonic", max.iter = 5, breaks = list(NULL, 4))
> ```
> 
> But this is because the sctest says there is no break, and the sctest overrides (runs prior to) bfast.

It seems that the strucchangeRcpp version isn't updated now, so where should I test it?

**Comment by xytu** [comment]
plot(fit, ANOVA = TRUE)  #β and P will be shown in each section of the trend component, but the output doesn't include these two parameters . How can I get these two values?

**Comment by GreatEmerald** [comment]
Pull #41 has been updated, just rerun `install_github("bfast2/strucchangeRcpp@40-numeric-breaks")` (and same for `bfast`).

**Comment by xytu** [comment]
fit <- bfast(harvest, h = rdist, season = "harmonic", max.iter = 5, breaks = list(NULL, 4))
#Error in match.arg(breaks) : 'arg' is either NULL or a character vector.

**Comment by GreatEmerald** [comment]
Are you sure you have run both:
```r
install_github("bfast2/strucchangeRcpp@40-numeric-breaks")
install_github("bfast2/bfast@40-numeric-breaks")
```

**Comment by xytu** [comment]
Working fine, thanks!
